In [1]:
!pip install opencv-python

## 1. Get acquainted with OpenCV

In [2]:
import cv2

In [4]:
# List all methods with cv2
# dir(cv2)

In [168]:
# Assign
color = cv2.imread('./galaxy.jpeg', 1)
# print(color)
print(f"Dimension number of color is: {color.ndim}")
print(f"Type of color is: {type(color)}")

Dimension number of color is: 3
Type of color is: <class 'numpy.ndarray'>


In [169]:
gray = cv2.imread('galaxy.jpeg', 0)
print(f"Dimension number of color is: {gray.ndim}")
print(f"Type of color is: {type(gray)}")

Dimension number of color is: 2
Type of color is: <class 'numpy.ndarray'>


In [170]:
# Export gray image to jpeg file
cv2.imwrite('galaxy-gray.jpeg', gray)

True

## 2. Exercise: Convert color images in a folder to grayscale

### Retrieve list of files in images folder

In [30]:
from pathlib import Path, PurePath

In [31]:
p = Path('.')
list(p.glob('*.*'))

[WindowsPath('.git'),
 WindowsPath('.gitignore'),
 WindowsPath('.ipynb_checkpoints'),
 WindowsPath('galaxy-gray.jpeg'),
 WindowsPath('galaxy.jpeg'),
 WindowsPath('image_processing.ipynb'),
 WindowsPath('README.md')]

In [109]:
# iterate through all folders and check if 'images' is in folder names
# pull the folder with index 0, and use glob to list all files in the images folder
images_folder = [folder for folder in p.iterdir() if (folder.is_dir() and 'images' in str(folder))][0].glob('*.*')

# check if jpeg in file extension
images = [image for image in images_folder if 'jpeg' in str(image)]

### Make new folder grayimages

In [127]:
new_folder = './grayimages'
Path(new_folder).mkdir(exist_ok=True)

In [166]:
print(type(str(images[0].as_posix())))

<class 'str'>


### Convert color images to grayscale then put them into grayimages folder
Lesson-learnt: Both imread and imwrite need file path as string, not Pathlib objects

In [175]:
for image in images:
    gray_file = cv2.imread(str(image.as_posix()), 0)
    cv2.imwrite(f"{new_folder}/gray_{image.name}", gray_file)

## 3. Resize Image

In [178]:
import cv2

image = cv2.imread('galaxy.jpeg')
print(image.shape) # Check size of image

(779, 438, 3)


In [28]:
import cv2
from pathlib import Path

def calculate_size(scale, width, height):
    scaled_width = int(width * scale/100)
    scaled_height = int(height * scale/100)
    return (scaled_width, scaled_height)

def resize_image(image_path, scale, interpolation=cv2.INTER_LINEAR, resized_folder='./resized'):
    """
    Options of interpolation:
    cv2.INTER_AREA: Preferable for reducing size
    cv2.INTER_CUBIC
    cv2.INTER_LINEAR
    cv2.INTER_NEAREST
    """
   
    # Scale type for scaled image name
    scale_int = str(interpolation)
    if scale_int == "0":
        scale_type = 'INTER_NEAREST'
    if scale_int == "1":
        scale_type = 'INTER_LINEAR'
    if scale_int == "2":
        scale_type = 'INTER_CUBIC'
    if scale_int == "3":
        scale_type = 'INTER_AREA'

    Path(resized_folder).mkdir(exist_ok=True) # Make new resized folder
    
    image = cv2.imread(image_path) # Read image
    [height, width, _] = image.shape # Extract image dimensions
    (scaled_width, scaled_height) = calculate_size(scale, width, height) # Calculated scaled size
    
    # Resize image
    resized_image = cv2.resize(src = image,
                               dsize = (scaled_width, scaled_height), 
                               interpolation=interpolation)
    
    # Write image
    cv2.imwrite(f'{resized_folder}/scale_{scale}pct_{scale_type}_{Path(image_path).name}', resized_image)    
    return resized_image

In [31]:
target_image = './resized/scale_20pct_INTER_NEAREST_galaxy.jpeg'

In [36]:
output = resize_image('galaxy.jpeg', 20, cv2.INTER_AREA )
resize_image(target_image, 2000, cv2.INTER_AREA )

array([[[7, 2, 4],
        [7, 2, 4],
        [7, 2, 4],
        ...,
        [3, 0, 2],
        [3, 0, 2],
        [3, 0, 2]],

       [[7, 2, 4],
        [7, 2, 4],
        [7, 2, 4],
        ...,
        [3, 0, 2],
        [3, 0, 2],
        [3, 0, 2]],

       [[7, 2, 4],
        [7, 2, 4],
        [7, 2, 4],
        ...,
        [3, 0, 2],
        [3, 0, 2],
        [3, 0, 2]],

       ...,

       [[3, 1, 1],
        [3, 1, 1],
        [3, 1, 1],
        ...,
        [6, 1, 2],
        [6, 1, 2],
        [6, 1, 2]],

       [[3, 1, 1],
        [3, 1, 1],
        [3, 1, 1],
        ...,
        [6, 1, 2],
        [6, 1, 2],
        [6, 1, 2]],

       [[3, 1, 1],
        [3, 1, 1],
        [3, 1, 1],
        ...,
        [6, 1, 2],
        [6, 1, 2],
        [6, 1, 2]]], dtype=uint8)

In [37]:
resize_image('galaxy.jpeg', 20, cv2.INTER_NEAREST )
resize_image(target_image, 2000, cv2.INTER_NEAREST )

array([[[7, 2, 4],
        [7, 2, 4],
        [7, 2, 4],
        ...,
        [3, 0, 2],
        [3, 0, 2],
        [3, 0, 2]],

       [[7, 2, 4],
        [7, 2, 4],
        [7, 2, 4],
        ...,
        [3, 0, 2],
        [3, 0, 2],
        [3, 0, 2]],

       [[7, 2, 4],
        [7, 2, 4],
        [7, 2, 4],
        ...,
        [3, 0, 2],
        [3, 0, 2],
        [3, 0, 2]],

       ...,

       [[3, 1, 1],
        [3, 1, 1],
        [3, 1, 1],
        ...,
        [6, 1, 2],
        [6, 1, 2],
        [6, 1, 2]],

       [[3, 1, 1],
        [3, 1, 1],
        [3, 1, 1],
        ...,
        [6, 1, 2],
        [6, 1, 2],
        [6, 1, 2]],

       [[3, 1, 1],
        [3, 1, 1],
        [3, 1, 1],
        ...,
        [6, 1, 2],
        [6, 1, 2],
        [6, 1, 2]]], dtype=uint8)

In [38]:
resize_image('galaxy.jpeg', 20, cv2.INTER_CUBIC)
resize_image(target_image, 2000, cv2.INTER_CUBIC)

array([[[7, 2, 4],
        [7, 2, 4],
        [7, 2, 4],
        ...,
        [3, 0, 2],
        [3, 0, 2],
        [3, 0, 2]],

       [[7, 2, 4],
        [7, 2, 4],
        [7, 2, 4],
        ...,
        [3, 0, 2],
        [3, 0, 2],
        [3, 0, 2]],

       [[7, 2, 4],
        [7, 2, 4],
        [7, 2, 4],
        ...,
        [3, 0, 2],
        [3, 0, 2],
        [3, 0, 2]],

       ...,

       [[3, 1, 1],
        [3, 1, 1],
        [3, 1, 1],
        ...,
        [6, 1, 2],
        [6, 1, 2],
        [6, 1, 2]],

       [[3, 1, 1],
        [3, 1, 1],
        [3, 1, 1],
        ...,
        [6, 1, 2],
        [6, 1, 2],
        [6, 1, 2]],

       [[3, 1, 1],
        [3, 1, 1],
        [3, 1, 1],
        ...,
        [6, 1, 2],
        [6, 1, 2],
        [6, 1, 2]]], dtype=uint8)

In [39]:
resize_image('galaxy.jpeg', 20, cv2.INTER_LINEAR )
resize_image(target_image, 2000, cv2.INTER_LINEAR )

array([[[7, 2, 4],
        [7, 2, 4],
        [7, 2, 4],
        ...,
        [3, 0, 2],
        [3, 0, 2],
        [3, 0, 2]],

       [[7, 2, 4],
        [7, 2, 4],
        [7, 2, 4],
        ...,
        [3, 0, 2],
        [3, 0, 2],
        [3, 0, 2]],

       [[7, 2, 4],
        [7, 2, 4],
        [7, 2, 4],
        ...,
        [3, 0, 2],
        [3, 0, 2],
        [3, 0, 2]],

       ...,

       [[3, 1, 1],
        [3, 1, 1],
        [3, 1, 1],
        ...,
        [6, 1, 2],
        [6, 1, 2],
        [6, 1, 2]],

       [[3, 1, 1],
        [3, 1, 1],
        [3, 1, 1],
        ...,
        [6, 1, 2],
        [6, 1, 2],
        [6, 1, 2]],

       [[3, 1, 1],
        [3, 1, 1],
        [3, 1, 1],
        ...,
        [6, 1, 2],
        [6, 1, 2],
        [6, 1, 2]]], dtype=uint8)